### ISSUE TITLE
Clock: Last test series doesn't call sub

### ISSUE THREAD

**Issue by DianaLaura** [exercism/perl5#466] opened 2022-06-21 10:07 UTC
Hi

I noticed that the last test series with the property "equals" doesn't actually call any subroutine (neither the already defined time() nor a specific one for these tests), which means that it always compares the input with the expected output (and usually fails at doing so). The test file also doesn't import an extra method for this test series, and the module doesn't contain any specific subroutine for these tests.

**Comment by m-dango** [comment] 2022-06-25 11:32
Hi @DianaLaura 

There is no need for the test to call any methods on the objects. The test is checking if the created clocks are equivalent or not e.g. a clock created with 0 as the hour and 24 as the hour will produce identical objects.

The test description states "Two clocks that represent the same time should be equal to each other." Perhaps it would be worth submitting your solution for mentoring?

This is the output of a solution which achieves this:

```
{
  clock1 => { hour => 15, minute => 37 },
  clock2 => { hour => 15, minute => 37 },
}
clock 1: bless({ hour => 15, minute => 37 }, "Clock")
clock 2: bless({ hour => 15, minute => 37 }, "Clock")

{
  clock1 => { hour => 10, minute => 37 },
  clock2 => { hour => 34, minute => 37 },
}
clock 1: bless({ hour => 10, minute => 37 }, "Clock")
clock 2: bless({ hour => 10, minute => 37 }, "Clock")

{
  clock1 => { hour => 3, minute => 11 },
  clock2 => { hour => 99, minute => 11 },
}
clock 1: bless({ hour => 3, minute => 11 }, "Clock")
clock 2: bless({ hour => 3, minute => 11 }, "Clock")

{
  clock1 => { hour => 22, minute => 40 },
  clock2 => { hour => -2, minute => 40 },
}
clock 1: bless({ hour => 22, minute => 40 }, "Clock")
clock 2: bless({ hour => 22, minute => 40 }, "Clock")

{
  clock1 => { hour => 17, minute => 3 },
  clock2 => { hour => -31, minute => 3 },
}
clock 1: bless({ hour => 17, minute => 3 }, "Clock")
clock 2: bless({ hour => 17, minute => 3 }, "Clock")

{
  clock1 => { hour => 13, minute => 49 },
  clock2 => { hour => -83, minute => 49 },
}
clock 1: bless({ hour => 13, minute => 49 }, "Clock")
clock 2: bless({ hour => 13, minute => 49 }, "Clock")

{
  clock1 => { hour => 0, minute => 1 },
  clock2 => { hour => 0, minute => 1441 },
}
clock 1: bless({ hour => 0, minute => 1 }, "Clock")
clock 2: bless({ hour => 0, minute => 1 }, "Clock")

{
  clock1 => { hour => 2, minute => 2 },
  clock2 => { hour => 2, minute => 4322 },
}
clock 1: bless({ hour => 2, minute => 2 }, "Clock")
clock 2: bless({ hour => 2, minute => 2 }, "Clock")

{
  clock1 => { hour => 2, minute => 40 },
  clock2 => { hour => 3, minute => -20 },
}
clock 1: bless({ hour => 2, minute => 40 }, "Clock")
clock 2: bless({ hour => 2, minute => 40 }, "Clock")

{
  clock1 => { hour => 4, minute => 10 },
  clock2 => { hour => 5, minute => -1490 },
}
clock 1: bless({ hour => 4, minute => 10 }, "Clock")
clock 2: bless({ hour => 4, minute => 10 }, "Clock")

{
  clock1 => { hour => 6, minute => 15 },
  clock2 => { hour => 6, minute => -4305 },
}
clock 1: bless({ hour => 6, minute => 15 }, "Clock")
clock 2: bless({ hour => 6, minute => 15 }, "Clock")

{
  clock1 => { hour => 7, minute => 32 },
  clock2 => { hour => -12, minute => -268 },
}
clock 1: bless({ hour => 7, minute => 32 }, "Clock")
clock 2: bless({ hour => 7, minute => 32 }, "Clock")

{
  clock1 => { hour => 18, minute => 7 },
  clock2 => { hour => -54, minute => -11513 },
}
clock 1: bless({ hour => 18, minute => 7 }, "Clock")
clock 2: bless({ hour => 18, minute => 7 }, "Clock")

{
  clock1 => { hour => 24, minute => 0 },
  clock2 => { hour => 0, minute => 0 },
}
clock 1: bless({ hour => 0, minute => 0 }, "Clock")
clock 2: bless({ hour => 0, minute => 0 }, "Clock")
```

**Comment by m-dango** [comment] 2022-06-25 13:26
I'm closing the issue as I believe the `equal` tests are functioning as intended i.e. checking two objects created via the `new` method, with different arguments that would result in having the same time, are identical. Feel free to reopen the issue if you suspect this behavior is not working correctly.

**Closed by m-dango** 2022-06-25 13:26 UTC

**Comment by DianaLaura** [comment] 2022-06-27 08:28
I admit that I didn't realise that the call was via the new-method (I'm still learning Pearl), but the new-method doesn't exist in the .pm file. The only three methods that are in the .pm file are time, add_minutes and subtract_minutes. The new-method is also not in the description.

The test cases are also calling the new-method several times, so I guess there was once a new-method, but the exercise was restructured, and someone forgot to adapt the test file. Interestingly, the missing new-method seems only to be a problem for the last test series, the other ones run through smoothly.

I can also hand in my solution for mentoring if you still don't believe me, but I passed every other test series except the last one where I couldn't even figure out what was going to be tested.

And I'm a professional software developer learning Perl, btw.

**Comment by m-dango** [comment] 2022-06-27 09:03
The `new` method is provided via the `Moo` module. Perl doesn't (yet) have its own built in object orientation system, and Moo is one of the most commonly used ones. I thought there was some additional documentation mentioning this somewhere along with a tutorial, but I'm either misremembering or it has gone missing at some point, so apologies for that.

You can read more about Moo here:
https://perlmaven.com/oop-with-moo
https://metacpan.org/pod/Moo

Alternatively, you can also remove `use Moo` and write your own `new` method if you wish.
